
# pvc backed by persistent disk
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-dest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  

